version: "3.9"
services:
  cardb:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "cars"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - .:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"

  enginedb:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "engines"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - .:/docker-entrypoint-initdb.d
    ports:
      - "5434:5432"