// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: gateway.proto

package gatewayService

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GatewayServiceClient is the client API for GatewayService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GatewayServiceClient interface {
	GetUserCars(ctx context.Context, in *GetUserCarsReq, opts ...grpc.CallOption) (*GetUserCarsRes, error)
	GetUserEngines(ctx context.Context, in *GetUserCarsReq, opts ...grpc.CallOption) (*GetUserEnginesRes, error)
	GetUserEnginesByBrand(ctx context.Context, in *GetUserCarsByBrandReq, opts ...grpc.CallOption) (*GetUserEnginesRes, error)
	GetUserEngineByCar(ctx context.Context, in *GetUserCarsReq, opts ...grpc.CallOption) (*GetUserEngineRes, error)
}

type gatewayServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGatewayServiceClient(cc grpc.ClientConnInterface) GatewayServiceClient {
	return &gatewayServiceClient{cc}
}

func (c *gatewayServiceClient) GetUserCars(ctx context.Context, in *GetUserCarsReq, opts ...grpc.CallOption) (*GetUserCarsRes, error) {
	out := new(GetUserCarsRes)
	err := c.cc.Invoke(ctx, "/gatewayService.GatewayService/GetUserCars", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) GetUserEngines(ctx context.Context, in *GetUserCarsReq, opts ...grpc.CallOption) (*GetUserEnginesRes, error) {
	out := new(GetUserEnginesRes)
	err := c.cc.Invoke(ctx, "/gatewayService.GatewayService/GetUserEngines", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) GetUserEnginesByBrand(ctx context.Context, in *GetUserCarsByBrandReq, opts ...grpc.CallOption) (*GetUserEnginesRes, error) {
	out := new(GetUserEnginesRes)
	err := c.cc.Invoke(ctx, "/gatewayService.GatewayService/GetUserEnginesByBrand", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) GetUserEngineByCar(ctx context.Context, in *GetUserCarsReq, opts ...grpc.CallOption) (*GetUserEngineRes, error) {
	out := new(GetUserEngineRes)
	err := c.cc.Invoke(ctx, "/gatewayService.GatewayService/GetUserEngineByCar", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GatewayServiceServer is the server API for GatewayService service.
// All implementations must embed UnimplementedGatewayServiceServer
// for forward compatibility
type GatewayServiceServer interface {
	GetUserCars(context.Context, *GetUserCarsReq) (*GetUserCarsRes, error)
	GetUserEngines(context.Context, *GetUserCarsReq) (*GetUserEnginesRes, error)
	GetUserEnginesByBrand(context.Context, *GetUserCarsByBrandReq) (*GetUserEnginesRes, error)
	GetUserEngineByCar(context.Context, *GetUserCarsReq) (*GetUserEngineRes, error)
	mustEmbedUnimplementedGatewayServiceServer()
}

// UnimplementedGatewayServiceServer must be embedded to have forward compatible implementations.
type UnimplementedGatewayServiceServer struct {
}

func (UnimplementedGatewayServiceServer) GetUserCars(context.Context, *GetUserCarsReq) (*GetUserCarsRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserCars not implemented")
}
func (UnimplementedGatewayServiceServer) GetUserEngines(context.Context, *GetUserCarsReq) (*GetUserEnginesRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserEngines not implemented")
}
func (UnimplementedGatewayServiceServer) GetUserEnginesByBrand(context.Context, *GetUserCarsByBrandReq) (*GetUserEnginesRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserEnginesByBrand not implemented")
}
func (UnimplementedGatewayServiceServer) GetUserEngineByCar(context.Context, *GetUserCarsReq) (*GetUserEngineRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserEngineByCar not implemented")
}
func (UnimplementedGatewayServiceServer) mustEmbedUnimplementedGatewayServiceServer() {}

// UnsafeGatewayServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GatewayServiceServer will
// result in compilation errors.
type UnsafeGatewayServiceServer interface {
	mustEmbedUnimplementedGatewayServiceServer()
}

func RegisterGatewayServiceServer(s grpc.ServiceRegistrar, srv GatewayServiceServer) {
	s.RegisterService(&GatewayService_ServiceDesc, srv)
}

func _GatewayService_GetUserCars_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserCarsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).GetUserCars(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gatewayService.GatewayService/GetUserCars",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).GetUserCars(ctx, req.(*GetUserCarsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_GetUserEngines_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserCarsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).GetUserEngines(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gatewayService.GatewayService/GetUserEngines",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).GetUserEngines(ctx, req.(*GetUserCarsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_GetUserEnginesByBrand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserCarsByBrandReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).GetUserEnginesByBrand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gatewayService.GatewayService/GetUserEnginesByBrand",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).GetUserEnginesByBrand(ctx, req.(*GetUserCarsByBrandReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_GetUserEngineByCar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserCarsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).GetUserEngineByCar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gatewayService.GatewayService/GetUserEngineByCar",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).GetUserEngineByCar(ctx, req.(*GetUserCarsReq))
	}
	return interceptor(ctx, in, info, handler)
}

// GatewayService_ServiceDesc is the grpc.ServiceDesc for GatewayService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GatewayService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gatewayService.GatewayService",
	HandlerType: (*GatewayServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserCars",
			Handler:    _GatewayService_GetUserCars_Handler,
		},
		{
			MethodName: "GetUserEngines",
			Handler:    _GatewayService_GetUserEngines_Handler,
		},
		{
			MethodName: "GetUserEnginesByBrand",
			Handler:    _GatewayService_GetUserEnginesByBrand_Handler,
		},
		{
			MethodName: "GetUserEngineByCar",
			Handler:    _GatewayService_GetUserEngineByCar_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gateway.proto",
}
